[package]
name = "sup-decode"
version = "0.1.0"
authors = ["Rob Ede <robjtede@icloud.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3"
chrono = "0.4"
log = "0.4"
image = "0.23"
iced = "0.1.0"
once_cell = "1.3.1"
iced_native = "0.2.0"
iced_wgpu = "0.2.0"
simple-matrix = "0.1.2"

[dev-dependencies]
hex-literal = "0.2"
