[package]
name = "sup-decode"
version = "0.1.0"
authors = ["Rob Ede <robjtede@icloud.com>"]
edition = "2024"
rust-version = "1.85"

[dependencies]
byteorder = "1.3"
chrono = "0.4"
log = "0.4"
image = "0.23"
iced = { version = "0.13", features = ["canvas"] }
iced_native = "0.10"
iced_wgpu = "0.13"
simple-matrix = "0.1.2"

[dev-dependencies]
hex-literal = "0.3"
